RACKET_INPLACE := third-party/racket/racket/
INPLACE_LIB_DIR := $(RACKET_INPLACE)lib/
INPLACE_INCLUDE_DIR := $(RACKET_INPLACE)include/
RACKET_CS_FRAMEWORK := $(INPLACE_LIB_DIR)Racket.framework
INSTALL_DIR := third-party/install/
INSTALL_INCLUDE_DIR := $(INSTALL_DIR)include/
INSTALL_LIB_DIR := $(INSTALL_DIR)lib/
INSTALL_FRAMEWORK_DIR := $(INSTALL_DIR)Frameworks/

.PHONY: all
all: install

$(RACKET_CS_FRAMEWORK):
	cd third-party/racket && $(MAKE) cs RACKETCS_SUFFIX=""

$(INSTALL_INCLUDE_DIR) $(INSTALL_LIB_DIR) $(INSTALL_FRAMEWORK_DIR):
	mkdir -p $@

.PHONY: install
install: $(RACKET_CS_FRAMEWORK) $(INSTALL_INCLUDE_DIR) $(INSTALL_LIB_DIR) $(INSTALL_FRAMEWORK_DIR)
	cp -R $(RACKET_CS_FRAMEWORK) $(INSTALL_FRAMEWORK_DIR)
	cp -R $(INPLACE_INCLUDE_DIR) $(INSTALL_INCLUDE_DIR)
